language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

before_install:
  - echo "before install!"
  - npm --version
  - yarn --version || npm install -g yarn
  - yarn global add @vue/cli

script:
  - ./gradlew clean
  - ./gradlew build
