os: linux
dist: trusty

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - yarn --version && yarn global add @vue/cli
      script:
        - ./gradlew build
