version: '3'

services:
  front:
    build: ./parkinglot-front
    ports:
      - 8001:8001
  api:
    build: ./parkinglot-api
    ports:
      - 8080:8080
  proxy:
    depends_on:
      - api
      - front
    networks:
      - backend
      - frontend
    build: ./proxy
    ports:
      - 80:8000
networks:
  backend:
  frontend:



