version: '3'

services:
  front:
    build: ./parkinglot-front
    networks:
      - frontend
#    ports:
#      - 8001:8001
  api:
    build: ./parkinglot-api
    networks:
      - backend
#    ports:
#      - 8080:8080
  proxy:
    build: ./proxy
    depends_on:
      - api
      - front
    networks:
      - backend
      - frontend
    ports:
      - 80:80
networks:
  backend:
  frontend:



