version: '3'

services:
  front:
    build: ./parkinglot-front
    networks:
      - frontend
  api:
    build: ./parkinglot-api
    environment:
      TZ: "Asia/Seoul"
    networks:
      - backend
  proxy:
    build: ./proxy
    depends_on:
      - api
      - front
    networks:
      - backend
      - frontend
    ports:
      - 80:80
networks:
  backend:
  frontend:



