# Common

spring:
  profiles:
    active: local

common:
  open-api:
    endpoint: http://openapi.seoul.go.kr:8088
    token: 6a756259796a756d32304559665677

---
# Local

spring:
  profiles: local

---
# mysql

spring:
  profiles: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: admin1!
      jdbc-url: jdbc:mysql://localhost:3306/parkinglot

---
# H2

spring:
  profiles: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: com.h2.Driver
