show tables;

create table parking_lot (
    ID numeric not null primary key,
    PARKING_NAME varchar(200) not null ,
    ADDR varchar(500) not null ,
    PARKING_CODE varchar(200) not null ,
    PARKING_TYPE varchar(200) not null ,
    PARKING_TYPE_NM varchar(200) not null ,
    OPERATION_RULE varchar(200) not null ,
    OPERATION_RULE_NM varchar(200) not null ,
    TEL varchar(200) not null ,
    QUE_STATUS varchar(200) not null ,
    QUE_STATUS_NM varchar(200) not null ,
    CAPACITY numeric not null ,
    CUR_PARKING numeric not null ,
    CUR_PARKING_TIME varchar(200) not null ,
    PAY_YN varchar(200) not null ,
    PAY_NM varchar(200) not null ,
    NIGHT_FREE_OPEN varchar(200) not null ,
    NIGHT_FREE_OPEN_NM varchar(200) not null ,
    WEEKDAY_BEGIN_TIME varchar(200) not null ,
    WEEKDAY_END_TIME varchar(200) not null ,
    WEEKEND_BEGIN_TIME varchar(200) not null ,
    WEEKEND_END_TIME varchar(200) not null ,
    HOLIDAY_BEGIN_TIME varchar(200) not null ,
    HOLIDAY_END_TIME varchar(200) not null ,
    SYNC_TIME varchar(200) not null ,
    SATURDAY_PAY_YN varchar(200) not null ,
    SATURDAY_PAY_NM varchar(200) not null ,
    HOLIDAY_PAY_YN varchar(200) not null ,
    HOLIDAY_PAY_NM varchar(200) not null ,
    FULLTIME_MONTHLY varchar(200) not null ,
    GRP_PARKNM varchar(200) not null ,
    RATES numeric not null ,
    TIME_RATE numeric not null ,
    ADD_RATES numeric not null ,
    ADD_TIME_RATE numeric not null ,
    BUS_RATES numeric not null ,
    BUS_TIME_RATE numeric not null ,
    BUS_ADD_TIME_RATE numeric not null ,
    BUS_ADD_RATES numeric not null ,
    DAY_MAXIMUM numeric not null ,
    LAT numeric not null ,
    LNG numeric not null ,
    ASSIGN_CODE varchar(200) not null ,
    ASSIGN_CODE_NM varchar(200) not null
);

