server:
  port: 80
logging:
  level:
    org.springframework.web: debug
spring:
  profiles:
    active: docker
---

# Local
spring:
  profiles: local
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8080
          order: 10000
          predicates:
            - Path=/api/**
        - id: front
          uri: http://localhost:8001
          order: 10000
          predicates:
            - Path=/front/**

---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://api:8080
          order: 10000
          predicates:
            - Path=/api/**
        - id: front
          uri: http://front:8001
          order: 10000
          predicates:
            - Path=/front/**
