# Common

spring:
  profiles:
    active: local

server:
  servlet:
    context-path: /api

common:
  open-api:
    endpoint: http://openapi.seoul.go.kr:8088
    token: 546b436f646a756d383078644e6d54
---
# Local

spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
# dev

spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin1!
      jdbc-url: jdbc:mysql://localhost:3306/parkinglot

